apiVersion: apps/v1
kind: Deployment
metadata:
  name: myreactapp1
  labels:
    app: react
spec:
  selector:
    matchLabels:
      app: react
  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
      - name: my-react-app-1
        image: hello-app:latest
# Use the localhost:32000 path to use image from registry service
# e.g.  image: localhost:32000/my-react-app-1:v3
        ports:
        - containerPort: 8080
